### ISSUE TITLE
update to new uBo version 1.27.6?

### ISSUE THREAD

**Issue by tmpm697** [jeremyperkin/FireFox-uBo-rice#1]
version 1.27.6 uses different layout and break this theme for it, can you update to latest uBo version?

**Comment by jeremyperkin** [comment]
Sorry not really keeping up with updating it.  Have been busy with uBo and
getting dark mode implemented

**Comment by jeremyperkin** [comment]
@tmpm697  This has now been updated.   If you want certain colors and not to go with the ones I used feel free to change them.

**Comment by tmpm697** [comment]
Thanks, I'll try it.

**Comment by tmpm697** [comment]
I like previous color more that use nord mainly, this new one added violet color `40/70/80` that make it almost unreadable.

**Comment by jeremyperkin** [comment]
Violet seems to be the way of the future for Firefox.

I will add variables before 8am tomorrow.

**Comment by jeremyperkin** [comment]
> I like previous color more that use nord mainly, this new one added violet color `40/70/80` that make it almost unreadable.

Have made the changes so that you can use it like before.  Enjoy!  new Method though as not as many files needed.
